import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SetTokenForm } from "@/features/create-order";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/shared/components/ui/card";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ token?: string }>;
}>) {
	const { token } = await params;

	return (
		<html
			lang="ru"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<main className={["flex flex-col justify-center h-full"]}>
					<section className="mx-auto w-full max-w-120 p-4 pb-0">
						<Card className="w-full">
							<CardHeader>
								<CardTitle>Подключение кассы</CardTitle>
								<CardDescription>
									Введите токен и загрузите справочники
								</CardDescription>
							</CardHeader>

							<CardContent>
								<SetTokenForm initialToken={token} />
							</CardContent>
						</Card>
					</section>

					{children}
				</main>
			</body>
		</html>
	);
}
